"""
Configuration file for model definitions and default parameters.
"""

MODELS = {
    "stabilityai/stable-diffusion-2-1-base": {
        "name": "Stable Diffusion 2.1",
        "short_name": "SD 2.1",
        "requires_safety_checker": False,
        "pipeline_class": "StableDiffusionPipeline",
        "diffusers_version": "0.10.0.dev0",
        "scheduler": ["diffusers", "PNDMScheduler"],
        "text_encoder": ["transformers", "CLIPTextModel"],
        "tokenizer": ["transformers", "CLIPTokenizer"],
        "unet": ["diffusers", "UNet2DConditionModel"],
        "vae": ["diffusers", "AutoencoderKL"],
        "feature_extractor": ["transformers", "CLIPImageProcessor"],
    },
    "stabilityai/stable-diffusion-xl-base-1.0": {
        "name": "Stable Diffusion XL",
        "short_name": "SDXL",
        "requires_safety_checker": False,
        "pipeline_class": "StableDiffusionXLPipeline",
        "diffusers_version": "0.19.0.dev0",
        "scheduler": ["diffusers", "EulerDiscreteScheduler"],
        "text_encoder": ["transformers", "CLIPTextModel"],
        "text_encoder_2": ["transformers", "CLIPTextModelWithProjection"],
        "tokenizer": ["transformers", "CLIPTokenizer"],
        "tokenizer_2": ["transformers", "CLIPTokenizer"],
        "unet": ["diffusers", "UNet2DConditionModel"],
        "vae": ["diffusers", "AutoencoderKL"],
        "force_zeros_for_empty_prompt": True,
        "add_watermarker": None,
    },
    "zai-org/CogView3-Plus-3B": {
        "name": "CogView3 Plus 3B",
        "short_name": "CogView3+",
        "requires_safety_checker": False,
        "pipeline_class": "CogView3PlusPipeline",
        "diffusers_version": "0.31.0.dev0",
        "scheduler": ["diffusers", "CogVideoXDDIMScheduler"],
        "text_encoder": ["transformers", "T5EncoderModel"],
        "tokenizer": ["transformers", "T5Tokenizer"],
        "transformer": ["diffusers", "CogView3PlusTransformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "PixArt-alpha/PixArt-XL-2-512x512": {
        "name": "PixArt-XL 2",
        "short_name": "PixArt-Alpha",
        "requires_safety_checker": False,
        "pipeline_class": "PixArtAlphaPipeline",
        "diffusers_version": "0.22.0.dev0",
        "scheduler": ["diffusers", "DPMSolverMultistepScheduler"],
        "text_encoder": ["transformers", "T5EncoderModel"],
        "tokenizer": ["transformers", "T5Tokenizer"],
        "transformer": ["diffusers", "Transformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "PixArt-alpha/PixArt-Sigma-XL-2-512-MS": {
        "name": "PixArt-Sigma XL 2",
        "short_name": "PixArt-Sigma",
        "requires_safety_checker": False,
        "pipeline_class": "PixArtSigmaPipeline",
        "diffusers_version": "0.22.0.dev0",
        "scheduler": ["diffusers", "DPMSolverMultistepScheduler"],
        "text_encoder": ["transformers", "T5EncoderModel"],
        "tokenizer": ["transformers", "T5Tokenizer"],
        "transformer": ["diffusers", "Transformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "Alpha-VLLM/Lumina-Next-SFT-diffusers": {
        "name": "Lumina-Next SFT",
        "short_name": "Lumina-Next",
        "requires_safety_checker": False,
        "pipeline_class": "LuminaText2ImgPipeline",
        "diffusers_version": "0.30.0.dev0",
        "scheduler": ["diffusers", "FlowMatchEulerDiscreteScheduler"],
        "text_encoder": ["transformers", "GemmaModel"],
        "tokenizer": ["transformers", "GemmaTokenizerFast"],
        "transformer": ["diffusers", "LuminaNextDiT2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "tencent/HunyuanDiT-v1.2-Diffusers": {
        "name": "HunyuanDiT v1.2",
        "short_name": "HunyuanDiT",
        "requires_safety_checker": True,
        "pipeline_class": "HunyuanDiT2DPipeline",
        "diffusers_version": "0.30.0.dev0",
        "scheduler": ["diffusers", "DDIMScheduler"],
        "text_encoder": ["transformers", "BertModel"],
        "text_encoder_2": ["transformers", "T5EncoderModel"],
        "tokenizer": ["transformers", "BertTokenizer"],
        "tokenizer_2": ["transformers", "T5Tokenizer"],
        "transformer": ["diffusers", "HunyuanDiT2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
        "feature_extractor": [None, None],
        "safety_checker": [None, None],
    },
    "stabilityai/stable-diffusion-3-medium-diffusers": {
        "name": "Stable Diffusion 3 Medium",
        "short_name": "SD 3",
        "requires_safety_checker": False,
        "pipeline_class": "StableDiffusion3Pipeline",
        "diffusers_version": "0.29.0.dev0",
        "scheduler": ["diffusers", "FlowMatchEulerDiscreteScheduler"],
        "text_encoder": ["transformers", "CLIPTextModelWithProjection"],
        "text_encoder_2": ["transformers", "CLIPTextModelWithProjection"],
        "text_encoder_3": ["transformers", "T5EncoderModel"],
        "tokenizer": ["transformers", "CLIPTokenizer"],
        "tokenizer_2": ["transformers", "CLIPTokenizer"],
        "tokenizer_3": ["transformers", "T5TokenizerFast"],
        "transformer": ["diffusers", "SD3Transformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "black-forest-labs/FLUX.1-dev": {
        "name": "FLUX.1 Dev",
        "short_name": "FLUX.1-dev",
        "requires_safety_checker": False,
        "pipeline_class": "FluxPipeline",
        "diffusers_version": "0.30.0.dev0",
        "scheduler": ["diffusers", "FlowMatchEulerDiscreteScheduler"],
        "text_encoder": ["transformers", "CLIPTextModel"],
        "text_encoder_2": ["transformers", "T5EncoderModel"],
        "tokenizer": ["transformers", "CLIPTokenizer"],
        "tokenizer_2": ["transformers", "T5TokenizerFast"],
        "transformer": ["diffusers", "FluxTransformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "Efficient-Large-Model/Sana_600M_512px_diffusers": {
        "name": "Sana 600M 512px",
        "short_name": "SANA",
        "requires_safety_checker": False,
        "pipeline_class": "SanaPipeline",
        "diffusers_version": "0.32.0.dev0",
        "scheduler": ["diffusers", "DPMSolverMultistepScheduler"],
        "text_encoder": ["transformers", "Gemma2Model"],
        "tokenizer": ["transformers", "GemmaTokenizerFast"],
        "transformer": ["diffusers", "SanaTransformer2DModel"],
        "vae": ["diffusers", "AutoencoderDC"],
    },
    "Qwen/Qwen-Image": {
        "name": "Qwen Image",
        "short_name": "Qwen-Image",
        "requires_safety_checker": False,
        "pipeline_class": "QwenImagePipeline",
        "diffusers_version": "0.34.0.dev0",
        "scheduler": ["diffusers", "FlowMatchEulerDiscreteScheduler"],
        "text_encoder": ["transformers", "Qwen2_5_VLForConditionalGeneration"],
        "tokenizer": ["transformers", "Qwen2Tokenizer"],
        "transformer": ["diffusers", "QwenImageTransformer2DModel"],
        "vae": ["diffusers", "AutoencoderKLQwenImage"],
    },
    "thu-ml/unidiffuser-v1": {
        "name": "UniDiffuser v1",
        "short_name": "UniDiffuser",
        "requires_safety_checker": False,
        "pipeline_class": "UniDiffuserPipeline",
        "diffusers_version": "0.21.0.dev0",
        "scheduler": ["diffusers", "DPMSolverMultistepScheduler"],
        "text_encoder": ["transformers", "CLIPTextModel"],
        "image_encoder": ["transformers", "CLIPVisionModelWithProjection"],
        "text_decoder": ["unidiffuser", "UniDiffuserTextDecoder"],
        "clip_tokenizer": ["transformers", "CLIPTokenizer"],
        "text_tokenizer": ["transformers", "GPT2Tokenizer"],
        "clip_image_processor": ["transformers", "CLIPImageProcessor"],
        "unet": ["unidiffuser", "UniDiffuserModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "stabilityai/stable-cascade": {
        "name": "Stable Cascade",
        "short_name": "Stable Cascade",
        "requires_safety_checker": False,
        "pipeline_class": "StableCascadeCombinedPipeline",
        "diffusers_version": "0.27.0.dev0",
        "scheduler": ["diffusers", "DDPMWuerstchenScheduler"],
        "text_encoder": ["transformers", "CLIPTextModelWithProjection"],
        "tokenizer": ["transformers", "CLIPTokenizerFast"],
        "decoder": ["diffusers", "StableCascadeUNet"],
        "vqgan": ["wuerstchen", "PaellaVQModel"],
        "latent_dim_scale": 10.67,
    },
    "zai-org/CogView4-6B": {
        "name": "CogView4 6B",
        "short_name": "CogView4",
        "requires_safety_checker": False,
        "pipeline_class": "CogView4Pipeline",
        "diffusers_version": "0.33.0.dev0",
        "scheduler": ["diffusers", "FlowMatchEulerDiscreteScheduler"],
        "text_encoder": ["transformers", "GlmModel"],
        "tokenizer": ["transformers", "PreTrainedTokenizerFast"],
        "transformer": ["diffusers", "CogView4Transformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "kandinsky-community/kandinsky-3": {
        "name": "Kandinsky 3",
        "short_name": "Kandinsky-3",
        "requires_safety_checker": False,
        "pipeline_class": "Kandinsky3Pipeline",
        "diffusers_version": "0.24.0.dev0",
        "scheduler": ["diffusers", "DDPMScheduler"],
        "text_encoder": ["transformers", "T5EncoderModel"],
        "tokenizer": ["transformers", "T5Tokenizer"],
        "unet": ["diffusers", "Kandinsky3UNet"],
        "movq": ["diffusers", "VQModel"],
    },
    "HiDream-ai/HiDream-I1-Dev": {
        "name": "HiDream I1 Dev",
        "short_name": "HiDream-I1",
        "requires_safety_checker": False,
        "pipeline_class": "HiDreamImagePipeline",
        "diffusers_version": "0.32.1",
        "scheduler": ["diffusers", "UniPCMultistepScheduler"],
        "text_encoder": ["transformers", "CLIPTextModelWithProjection"],
        "text_encoder_2": ["transformers", "CLIPTextModelWithProjection"],
        "text_encoder_3": ["transformers", "T5EncoderModel"],
        "text_encoder_4": ["transformers", "LlamaForCausalLM"],
        "tokenizer": ["transformers", "CLIPTokenizer"],
        "tokenizer_2": ["transformers", "CLIPTokenizer"],
        "tokenizer_3": ["transformers", "T5Tokenizer"],
        "tokenizer_4": ["transformers", "PreTrainedTokenizerFast"],
        "transformer": ["diffusers", "HiDreamImageTransformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "Efficient-Large-Model/SANA1.5_1.6B_1024px_diffusers": {
        "name": "SANA 1.5 1.6B 1024px",
        "short_name": "SANA 1.5",
        "requires_safety_checker": False,
        "pipeline_class": "SanaPipeline",
        "diffusers_version": "0.33.0.dev0",
        "scheduler": ["diffusers", "DPMSolverMultistepScheduler"],
        "text_encoder": ["transformers", "Gemma2Model"],
        "tokenizer": ["transformers", "GemmaTokenizerFast"],
        "transformer": ["diffusers", "SanaTransformer2DModel"],
        "vae": ["diffusers", "AutoencoderDC"],
    },
    "Alpha-VLLM/Lumina-Image-2.0": {
        "name": "Lumina Image 2.0",
        "short_name": "Lumina-Image-2.0",
        "requires_safety_checker": False,
        "pipeline_class": "Lumina2Pipeline",
        "diffusers_version": "0.33.0.dev0",
        "scheduler": ["diffusers", "FlowMatchEulerDiscreteScheduler"],
        "text_encoder": ["transformers", "Gemma2Model"],
        "tokenizer": ["transformers", "GemmaTokenizerFast"],
        "transformer": ["diffusers", "Lumina2Transformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "stabilityai/stable-diffusion-3-5-large": {
        "name": "Stable Diffusion 3.5 Large",
        "short_name": "SD 3.5 Large",
        "requires_safety_checker": False,
        "pipeline_class": "StableDiffusion3Pipeline",
        "diffusers_version": "0.30.3.dev0",
        "scheduler": ["diffusers", "FlowMatchEulerDiscreteScheduler"],
        "text_encoder": ["transformers", "CLIPTextModelWithProjection"],
        "text_encoder_2": ["transformers", "CLIPTextModelWithProjection"],
        "text_encoder_3": ["transformers", "T5EncoderModel"],
        "tokenizer": ["transformers", "CLIPTokenizer"],
        "tokenizer_2": ["transformers", "CLIPTokenizer"],
        "tokenizer_3": ["transformers", "T5TokenizerFast"],
        "transformer": ["diffusers", "SD3Transformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "HiDream-ai/HiDream-I1-Full": {
        "name": "HiDream I1 Full",
        "short_name": "HiDream-I1-Full",
        "requires_safety_checker": False,
        "pipeline_class": "HiDreamImagePipeline",
        "diffusers_version": "0.32.1",
        "scheduler": ["diffusers", "UniPCMultistepScheduler"],
        "text_encoder": ["transformers", "CLIPTextModelWithProjection"],
        "text_encoder_2": ["transformers", "CLIPTextModelWithProjection"],
        "text_encoder_3": ["transformers", "T5EncoderModel"],
        "text_encoder_4": ["transformers", "LlamaForCausalLM"],
        "tokenizer": ["transformers", "CLIPTokenizer"],
        "tokenizer_2": ["transformers", "CLIPTokenizer"],
        "tokenizer_3": ["transformers", "T5Tokenizer"],
        "tokenizer_4": ["transformers", "PreTrainedTokenizerFast"],
        "transformer": ["diffusers", "HiDreamImageTransformer2DModel"],
        "vae": ["diffusers", "AutoencoderKL"],
    },
    "kandinsky-community/kandinsky-2-1": {
        "name": "Kandinsky 2.1",
        "short_name": "Kandinsky-2.1",
        "requires_safety_checker": False,
        "pipeline_class": "KandinskyPipeline",
        "diffusers_version": "0.17.0.dev0",
        "scheduler": ["diffusers", "DDIMScheduler"],
        "text_encoder": ["kandinsky", "MultilingualCLIP"],
        "tokenizer": ["transformers", "XLMRobertaTokenizerFast"],
        "unet": ["diffusers", "UNet2DConditionModel"],
        "movq": ["diffusers", "VQModel"],
    },
}

# Default models configuration (deprecated - no longer used since user mode was removed)
# Models are now loaded manually in developer mode or automatically in batch mode
DEFAULT_MODELS = []

# Unified scheduler configuration
# Models are categorized by their training paradigm
FLOW_MATCHING_MODELS = [
    "black-forest-labs/FLUX.1-dev",
    "stabilityai/stable-diffusion-3-medium-diffusers",
    "stabilityai/stable-diffusion-3-5-large",
    "Alpha-VLLM/Lumina-Next-SFT-diffusers",
    "Efficient-Large-Model/Sana_600M_512px_diffusers",
    "Efficient-Large-Model/SANA1.5_1.6B_1024px_diffusers",
    "Qwen/Qwen-Image",
    "Alpha-VLLM/Lumina-Image-2.0",
    "HiDream-ai/HiDream-I1-Full",
    "zai-org/CogView4-6B",
]

DIFFUSION_MODELS = [
    "stabilityai/stable-diffusion-2-1-base",
    "stabilityai/stable-diffusion-xl-base-1.0",
    "zai-org/CogView3-Plus-3B",
    "PixArt-alpha/PixArt-XL-2-512x512",
    "PixArt-alpha/PixArt-Sigma-XL-2-512-MS",
    "tencent/HunyuanDiT-v1.2-Diffusers",
    "thu-ml/unidiffuser-v1",
    "kandinsky-community/kandinsky-3",
    "kandinsky-community/kandinsky-2-1",
]

# Stable Cascade uses a special scheduler and architecture
SPECIAL_SCHEDULER_MODELS = [
    "stabilityai/stable-cascade",
]

# Enable unified scheduler (set to False to use model's original scheduler)
USE_UNIFIED_SCHEDULER = False

# Default generation parameters
DEFAULT_CONFIG = {
    "num_inference_steps": 50,
    "guidance_scale": 7.5,  # Classifier-free guidance scale for prompt adherence
    "width": 512,
    "height": 512,
    "seed": -1,  # -1 means random
    "negative_prompt": "",
    "use_unified_scheduler": False,  # Apply EulerDiscreteScheduler or FlowMatchEulerDiscreteScheduler
    "enable_profiling": True,  # Enable FLOPs/MACs computation profiling during inference
}

# Image size presets
IMAGE_SIZE_PRESETS = {
    "512x512": (512, 512),
    "768x768": (768, 768),
    "1024x1024": (1024, 1024),
    "1024x768 (Landscape)": (1024, 768),
    "768x1024 (Portrait)": (768, 1024),
    "1280x720 (16:9)": (1280, 720),
    "720x1280 (9:16)": (720, 1280),
}

# Output directory
OUTPUT_DIR = "outputs"

# Compute profiling configuration
ENABLE_COMPUTE_PROFILING = True  # Global flag to enable/disable FLOPs and MACs calculation

# Local model folder path
LOCAL_MODEL_DIR = "/data/liuzicheng/zhenyuan/models"

# Closed-source API model configurations
CLOSED_SOURCE_MODELS = {
    "openai": {
        "name": "OpenAI DALL-E",
        "short_name": "DALL-E 3",
        "models": ["dall-e-2", "dall-e-3"],
        "default_model": "dall-e-3",
        "supports_quality": True,
        "supports_style": True,
        "max_size": 1792,
        "api_key_env": "OPENAI_API_KEY",
    },
    "google": {
        "name": "Google Imagen",
        "short_name": "Imagen",
        "models": ["imagegeneration@005"],
        "default_model": "imagegeneration@005",
        "supports_quality": False,
        "supports_style": False,
        "max_size": 1536,
        "api_key_env": "GOOGLE_API_KEY",
        "additional_env": ["GOOGLE_PROJECT_ID"],
    },
    "bytedance": {
        "name": "Bytedance Cloud",
        "short_name": "Bytedance",
        "models": ["text2img-v1"],
        "default_model": "text2img-v1",
        "supports_quality": False,
        "supports_style": False,
        "max_size": 2048,
        "api_key_env": "BYTEDANCE_API_KEY",
    },
    "kling": {
        "name": "Kling AI",
        "short_name": "Kling",
        "models": ["kling-v1", "kling-v1-pro"],
        "default_model": "kling-v1",
        "supports_quality": False,
        "supports_style": False,
        "max_size": 2048,
        "api_key_env": "KLING_API_KEY",
    },
    "seeddream": {
        "name": "SeedDream 3.0",
        "short_name": "SeedDream",
        "models": ["high_aes_general_v30l_zt2i"],
        "default_model": "high_aes_general_v30l_zt2i",
        "supports_quality": False,
        "supports_style": False,
        "max_size": 2048,
        "api_key_env": "SEEDDREAM_ACCESS_KEY_ID",
        "additional_env": ["SEEDDREAM_SECRET_ACCESS_KEY"],
    }
}
